security:
    enable_authenticator_manager: true

    providers:
        app_user_provider:
            memory:
                users:
                    user@example.com:
                        password: '$2y$13$examplehashedpassword'
                        roles: ['ROLE_USER']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password

        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
                
    access_control:
        - { path: ^/api, roles: ROLE_API }